FROM golang:1.23 AS courier
WORKDIR /src
COPY cmd/* ./
RUN go build -o /courier ./...

FROM courier AS courier-test
#    ^ d: Dockerfile.courier:1
RUN go test ./...

FROM scratch AS parcel
COPY --from=courier /courier /
#           ^ d: Dockerfile.courier:1
COPY --from=courier-test /src/report.txt /
#           ^ d: Dockerfile.courier:6
COPY --from=build-env /src /src
#           ^ d: none
