@Library('pipeline-library') _

def deploy(target) {
    echo target
    //   ^ d: Jenkinsfile:3
}

node {
    stage('Build') {
  //^ d: none
        shipPlugin(timeout: 60)
      //^ d: vars/shipPlugin.groovy:3
        // status: shipPlugin: by name, 1 match
        notifyTeam()
      //^ d: vars/notifyTeam.groovy:1
        sh 'make'
      //^ d: none
        deploy('prod')
      //^ d: Jenkinsfile:3
        rollOut(region: 'us')
      //^ d: vars/rollOut.groovy:5
        notifyTeam.send('ops')
      //^ d: vars/notifyTeam.groovy:1
        //         ^ d: vars/notifyTeam.groovy:1
    }
}
